/* eslint-disable */
/**
 * Generated by scripts/generate-types.mjs.
 * Do not edit by hand; update the source schema and run npm run generate.
 */

/**
 * Endpoint input, query, and output DTOs published by job-events.v2.schema.json.
 */
export type JobEventsSchema = JobEventListView | ListJobEventsQuery;
/**
 * 可安全跨线传输的任意 JSON 值；用于 provider 扩展 options 与事件 payload。
 */
export type JsonValue =
  null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export interface JobEventListView {
  protocol_version: 2;
  /**
   * @maxItems 500
   */
  items: JobEventRecord[];
  next_cursor: string;
  has_more: boolean;
  limit: number;
}
/**
 * translation.rs :: JobEventRecord 的公开序列化形状。payload 保留递归 JSON 类型，不再退化为 {}。
 */
export interface JobEventRecord {
  job_id: string;
  /**
   * Persistent feed import order, not presentation or source order.
   */
  seq: number;
  ts: string;
  created_at?: string;
  level: string;
  lane: string | null;
  display_stage?: string;
  stage: string | null;
  substage: string | null;
  stage_detail: string | null;
  provider: string | null;
  provider_stage: string | null;
  event: string;
  event_type: string | null;
  raw_event_type: string | null;
  raw?: JobEventRawView;
  progress?: JobEventProgressView;
  message: string;
  retry_count: number | null;
  elapsed_ms: number | null;
  payload: JsonValue;
  event_id: string;
}
/**
 * 事件进入 API 归一化之前的来源追踪字段。
 */
export interface JobEventRawView {
  source_kind?: string;
  source_seq?: number;
  stage?: string;
  user_stage?: string;
  event_type?: string;
}
/**
 * translation.rs :: JobEventProgressView。字段为可选，因为未知进度可序列化为空对象。
 */
export interface JobEventProgressView {
  unit?: string;
  current?: number;
  total?: number;
  percent?: number;
}
/**
 * Use start for the first page or cursor for continuation, never both. Offset is rejected. Limit is clamped to 1..500. Head pagination has a fixed upper bound.
 */
export interface ListJobEventsQuery {
  limit?: number;
  start?: "head" | "tail";
  cursor?: string;
}
